name: Correctness Check (nuitka)

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.8"

      - name: Set up Python
        run: uv python install

      - name: Build with Nuitka # Workaround
        run: |
          cd nuitka && \
          uv export --no-hashes -o requirements.txt && \
          python -m venv .venv && \
          source .venv/bin/activate && \
          pip install -r requirements.txt && \
          nuitka --output-filename=partdiff main.py

      - name: Run correctness check
        uses: parcio/partdiff_tester@v0.1.9
        with:
          executable: "uv run main.py"
          cwd: "../nuitka"
          strictness: "4"
          shuffle: "42"
          filter: '[
            "o:{\"lines\": \"0\"}"
          ]'
